spring.application.name=GameLibraryAPI

#DB URL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GameLibraryDB;encrypt=true;trustServerCertificate=true;integratedSecurity=true;

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=sa
#spring.datasource.password=password

# JPA/Hibernate Properties (optional)
# Use the naming strategy property to force the names as displayed in java code.
# this avoids hibernate inserting underscores or spaces where there shouldn't be
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
#spring.show-sql=true